/* ===== Campings & pontos de apoio do Brasil — curadoria verificada =====
   Camada NACIONAL, independente dos roteiros. Consumida por campings-brasil.html.
   Cada ponto: { n, uf, reg, tipo, lat, lng, nota }
   tipo: camping | pernoite | apoio | parque
   Coordenadas aproximadas (nível do acesso/portaria) — confirme no iOverlander/local antes de ir.
   Para AMPLIAR: importe um GPX/CSV do iOverlander e acrescente aqui no mesmo formato. */
window.CAMPINGS_BR = [

  /* ===================== SUL ===================== */
  { n:"Camping do PARNA Aparados da Serra (Itaimbezinho)", uf:"RS", reg:"Sul", tipo:"parque", lat:-29.1667, lng:-50.0833, nota:"Base para o Cânion Itaimbezinho em Cambará do Sul; campings na vila e no entorno do parque." },
  { n:"Camping Cambará do Sul", uf:"RS", reg:"Sul", tipo:"camping", lat:-29.0483, lng:-50.1447, nota:"Vila-base dos cânions (Fortaleza e Itaimbezinho); várias áreas de camping e apoio." },
  { n:"Praia Grande (SC) — base dos cânions", uf:"SC", reg:"Sul", tipo:"apoio", lat:-29.1953, lng:-49.9622, nota:"Acesso aos cânions pelo pé da serra; campings e apoio a motorhome." },
  { n:"Camping São José dos Ausentes", uf:"RS", reg:"Sul", tipo:"camping", lat:-28.7486, lng:-49.9128, nota:"Campos de Cima da Serra; frio intenso, cachoeiras e cavalgadas." },
  { n:"Praia do Rosa (Imbituba)", uf:"SC", reg:"Sul", tipo:"camping", lat:-28.1281, lng:-48.6417, nota:"Enseada de surfe e baleias-franca (jun–nov); campings e pousadas." },
  { n:"Guarda do Embaú", uf:"SC", reg:"Sul", tipo:"camping", lat:-27.8964, lng:-48.5850, nota:"Vila de surfe com travessia de rio; campings próximos à praia." },
  { n:"Bombinhas", uf:"SC", reg:"Sul", tipo:"camping", lat:-27.1386, lng:-48.4814, nota:"Mar transparente e mergulho (Arvoredo); campings na península." },
  { n:"Lagoa da Conceição (Florianópolis)", uf:"SC", reg:"Sul", tipo:"apoio", lat:-27.6028, lng:-48.4675, nota:"Base central da Ilha; dunas, lagoa e apoio completo." },
  { n:"Urubici — Serra Catarinense", uf:"SC", reg:"Sul", tipo:"camping", lat:-28.0153, lng:-49.5925, nota:"Morro da Igreja, cânions e astroturismo; campings rurais e cachoeiras." },
  { n:"Camping Vale Europeu (Pomerode)", uf:"SC", reg:"Sul", tipo:"apoio", lat:-26.7408, lng:-49.1786, nota:"Rota do enxaimel e cervejarias; apoio no Vale do Itajaí." },
  { n:"Gramado / Canela", uf:"RS", reg:"Sul", tipo:"apoio", lat:-29.3628, lng:-50.8103, nota:"Serra Gaúcha; base de apoio, cascata do Caracol e Vale da Ferradura." },
  { n:"Camping Vale dos Vinhedos (Bento Gonçalves)", uf:"RS", reg:"Sul", tipo:"apoio", lat:-29.1667, lng:-51.5333, nota:"Enoturismo; vinícolas e apoio a motorhome no vale." },
  { n:"Ilha do Mel (base Pontal do Sul)", uf:"PR", reg:"Sul", tipo:"apoio", lat:-25.5711, lng:-48.3542, nota:"Travessia de barco; campings na ilha, sem carros." },
  { n:"Superagui / Guaraqueçaba", uf:"PR", reg:"Sul", tipo:"parque", lat:-25.4319, lng:-48.2242, nota:"Parque Nacional do litoral paranaense; acesso por barco." },
  { n:"Vila Velha (Ponta Grossa)", uf:"PR", reg:"Sul", tipo:"parque", lat:-25.2406, lng:-49.9975, nota:"Arenitos e formações rochosas; parque estadual com apoio na cidade." },
  { n:"Camping Fazenda Evaristo (Rio Negrinho)", uf:"SC", reg:"Sul", tipo:"camping", lat:-26.2919, lng:-49.4653, nota:"Apresentado como o maior camping do Brasil (~2 mi de m²); estrutura completa para barraca e motorhome, no planalto norte catarinense. Coord. aproximada." },
  { n:"Farol de Santa Marta (Laguna)", uf:"SC", reg:"Sul", tipo:"camping", lat:-28.6033, lng:-48.8092, nota:"Maior farol das Américas em alvenaria; costão, praias e campings rústicos." },
  { n:"Prudentópolis — cachoeiras", uf:"PR", reg:"Sul", tipo:"camping", lat:-25.2131, lng:-50.9772, nota:"Terra das quedas gigantes (Salto São Francisco, 196 m); campings e cânions." },
  { n:"Marumbi (Morretes)", uf:"PR", reg:"Sul", tipo:"parque", lat:-25.4406, lng:-48.9203, nota:"Serra do Mar paranaense; trilhas de montanha e camping do parque." },
  { n:"Foz do Iguaçu", uf:"PR", reg:"Sul", tipo:"apoio", lat:-25.5163, lng:-54.5854, nota:"Cataratas do Iguaçu e Itaipu; grande apoio e áreas de RV." },
  { n:"Torres — Parque da Guarita", uf:"RS", reg:"Sul", tipo:"camping", lat:-29.3353, lng:-49.7278, nota:"Falésias à beira-mar e o único cânion litorâneo do RS; campings e Camping Clube na cidade." },
  { n:"Cânion Fortaleza (Cambará do Sul)", uf:"RS", reg:"Sul", tipo:"parque", lat:-29.0525, lng:-50.0656, nota:"Paredões de ~900 m e a vista do Paredão; PARNA da Serra Geral, com campings na vila." },
  { n:"Serra do Rio do Rastro (Bom Jardim da Serra)", uf:"SC", reg:"Sul", tipo:"apoio", lat:-28.3897, lng:-49.6169, nota:"Estrada-mirante em ziguezague; base para a serra catarinense e São Joaquim." },
  { n:"Guartelá (Tibagi)", uf:"PR", reg:"Sul", tipo:"parque", lat:-24.5678, lng:-50.2569, nota:"Um dos maiores cânions em extensão do mundo; campings e rafting no rio Iapó." },
  { n:"Balneário Camboriú / Praia do Estaleiro", uf:"SC", reg:"Sul", tipo:"camping", lat:-27.0294, lng:-48.6178, nota:"Praias preservadas ao sul da cidade; campings de mata atlântica." },
  { n:"Garopaba / Ferrugem", uf:"SC", reg:"Sul", tipo:"camping", lat:-28.0281, lng:-48.6178, nota:"Praias de surfe e baleias; muitos campings próximos à Ferrugem e à Silveira." },
  { n:"Matinhos / Caiobá", uf:"PR", reg:"Sul", tipo:"apoio", lat:-25.8231, lng:-48.5411, nota:"Litoral paranaense; apoio de praia e base para Guaratuba e a Serra do Mar." },
  { n:"São Francisco de Paula — Fazenda do Salso", uf:"RS", reg:"Sul", tipo:"camping", lat:-29.4478, lng:-50.5836, nota:"Araucárias e lagos dos Campos de Cima da Serra; campings rurais e Cânion do Rio dos Corvos." },
  { n:"Praia do Cassino (Rio Grande)", uf:"RS", reg:"Sul", tipo:"camping", lat:-32.1719, lng:-52.1650, nota:"Uma das praias mais extensas do mundo; campings e o naufrágio do Altair no extremo sul gaúcho." },
  { n:"Nova Petrópolis", uf:"RS", reg:"Sul", tipo:"apoio", lat:-29.3764, lng:-51.1144, nota:"Jardim da Serra Gaúcha e cultura alemã; apoio e praticidade para motorhome." },
  { n:"Iraí — termas", uf:"RS", reg:"Sul", tipo:"apoio", lat:-27.1919, lng:-53.2508, nota:"Estância hidromineral no noroeste gaúcho; parque de águas termais e apoio." },
  { n:"Guaratuba", uf:"PR", reg:"Sul", tipo:"apoio", lat:-25.8825, lng:-48.5747, nota:"Baía e praias ao sul do litoral paranaense; apoio e travessia de ferry." },
  { n:"Treze Tílias", uf:"SC", reg:"Sul", tipo:"apoio", lat:-26.9989, lng:-51.4028, nota:"'Tirol brasileiro' no meio-oeste catarinense; apoio, escultura e gastronomia austríaca." },
  { n:"Antônio Prado / Caminhos de Pedra", uf:"RS", reg:"Sul", tipo:"apoio", lat:-28.8508, lng:-51.2833, nota:"Maior acervo de casas italianas tombadas do Brasil; roteiro rural dos Caminhos de Pedra." },
  { n:"São Joaquim", uf:"SC", reg:"Sul", tipo:"apoio", lat:-28.2939, lng:-49.9319, nota:"Cidade mais fria do Brasil; maçãs, vinhos de altitude e neve ocasional no inverno." },
  { n:"Lages / Coxilha Rica", uf:"SC", reg:"Sul", tipo:"camping", lat:-27.8150, lng:-50.3261, nota:"Berço do turismo rural; fazendas históricas, cascatas e céu estrelado no planalto serrano." },
  { n:"Blumenau", uf:"SC", reg:"Sul", tipo:"apoio", lat:-26.9194, lng:-49.0661, nota:"Vila Germânica, Oktoberfest e cervejarias; apoio central do Vale do Itajaí." },
  { n:"Porto Alegre", uf:"RS", reg:"Sul", tipo:"apoio", lat:-30.0346, lng:-51.2177, nota:"Capital gaúcha às margens do Guaíba; apoio urbano e base para a Serra e o litoral norte." },
  { n:"Caxias do Sul", uf:"RS", reg:"Sul", tipo:"apoio", lat:-29.1634, lng:-51.1797, nota:"Maior polo da Serra Gaúcha; apoio e porta de entrada para o Vale dos Vinhedos." },
  { n:"Pelotas", uf:"RS", reg:"Sul", tipo:"apoio", lat:-31.7654, lng:-52.3376, nota:"Casarões históricos e doces coloniais; apoio no sul do estado, perto do Cassino." },
  { n:"São Miguel das Missões", uf:"RS", reg:"Sul", tipo:"apoio", lat:-28.5567, lng:-54.5433, nota:"Ruínas jesuíticas guaranis, Patrimônio da Humanidade; apoio na vila e espetáculo de som e luz." },
  { n:"Santa Vitória do Palmar / Taim", uf:"RS", reg:"Sul", tipo:"camping", lat:-33.5189, lng:-53.3681, nota:"Extremo sul gaúcho; Estação Ecológica do Taim, lagoas e observação de aves." },
  { n:"Capão da Canoa", uf:"RS", reg:"Sul", tipo:"camping", lat:-29.7447, lng:-50.0092, nota:"Litoral norte gaúcho; praias movimentadas e campings próximos à orla." },
  { n:"Tramandaí", uf:"RS", reg:"Sul", tipo:"camping", lat:-29.9850, lng:-50.1339, nota:"Balneário histórico do litoral norte do RS; farol, praia e campings de temporada." },
  { n:"Joinville", uf:"SC", reg:"Sul", tipo:"apoio", lat:-26.3044, lng:-48.8464, nota:"Maior cidade de SC, tradição de imigração alemã e a Festa das Flores; apoio urbano." },
  { n:"Chapecó", uf:"SC", reg:"Sul", tipo:"apoio", lat:-27.1004, lng:-52.6152, nota:"Polo agroindustrial do oeste catarinense; apoio para quem segue rumo ao interior." },
  { n:"Penha", uf:"SC", reg:"Sul", tipo:"camping", lat:-26.7719, lng:-48.6453, nota:"Beto Carrero World e praias familiares no litoral norte de SC; campings próximos." },
  { n:"São Francisco do Sul", uf:"SC", reg:"Sul", tipo:"camping", lat:-26.2434, lng:-48.6386, nota:"Cidade mais antiga de SC, centro histórico e praias da ilha; campings e apoio." },
  { n:"Pontal do Paraná", uf:"PR", reg:"Sul", tipo:"camping", lat:-25.6711, lng:-48.3611, nota:"Balneários do litoral paranaense entre Matinhos e a Ilha do Mel; campings de praia." },
  { n:"Guarapuava", uf:"PR", reg:"Sul", tipo:"apoio", lat:-25.3897, lng:-51.4617, nota:"Portal dos Campos Gerais no centro-sul do PR; apoio para o Salto das Águas e a região." },
  { n:"Antonina", uf:"PR", reg:"Sul", tipo:"apoio", lat:-25.4306, lng:-48.7128, nota:"Baía histórica ao lado de Morretes, na Serra do Mar paranaense; apoio e patrimônio colonial." },

  /* ===================== SUDESTE ===================== */
  { n:"Camping Clube — Ubatuba (Perequê-Açu)", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-23.4108, lng:-45.0733, nota:"Unidade do Camping Clube do Brasil no litoral norte paulista." },
  { n:"Camping Clube — Ilhabela", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-23.7781, lng:-45.3581, nota:"Ilha de praias e cachoeiras; unidade tradicional do Camping Clube." },
  { n:"Camping do PARNA Serra da Bocaina", uf:"SP", reg:"Sudeste", tipo:"parque", lat:-23.3400, lng:-44.7900, nota:"Trilha do Ouro (Trindade–Paraty); montanha e mata atlântica." },
  { n:"Trindade (Paraty)", uf:"RJ", reg:"Sudeste", tipo:"camping", lat:-23.3639, lng:-44.6900, nota:"Vila de praias e piscina natural; muitos campings pé na areia." },
  { n:"Paraty — centro histórico", uf:"RJ", reg:"Sudeste", tipo:"apoio", lat:-23.2178, lng:-44.7131, nota:"Base colonial da Costa Verde; apoio e passeios de escuna." },
  { n:"Ilha Grande (base Angra/Conceição)", uf:"RJ", reg:"Sudeste", tipo:"apoio", lat:-23.0069, lng:-44.3181, nota:"Travessia de barco; campings em Abraão e praias." },
  { n:"Camping do PARNA Itatiaia (parte baixa)", uf:"RJ", reg:"Sudeste", tipo:"parque", lat:-22.4497, lng:-44.6169, nota:"Primeiro parque nacional do Brasil; camping e trilhas na mata." },
  { n:"Camping Clube — Penedo/Itatiaia", uf:"RJ", reg:"Sudeste", tipo:"camping", lat:-22.4392, lng:-44.5289, nota:"Base para a parte alta do Itatiaia (Agulhas Negras)." },
  { n:"Visconde de Mauá", uf:"RJ", reg:"Sudeste", tipo:"camping", lat:-22.3306, lng:-44.5450, nota:"Vale de cachoeiras na Mantiqueira; campings rurais." },
  { n:"Campos do Jordão / Horto Florestal", uf:"SP", reg:"Sudeste", tipo:"apoio", lat:-22.6867, lng:-45.4611, nota:"Mantiqueira paulista; araucárias, apoio e clima de montanha." },
  { n:"São Bento do Sapucaí (Pedra do Baú)", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-22.6892, lng:-45.7306, nota:"Escalada e trilhas na Pedra do Baú; campings rurais." },
  { n:"São Francisco Xavier", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-22.9000, lng:-45.9639, nota:"Refúgio de mata atlântica; cachoeiras e campings." },
  { n:"Socorro — Circuito das Águas", uf:"SP", reg:"Sudeste", tipo:"apoio", lat:-22.5911, lng:-46.5289, nota:"Turismo de aventura acessível; rafting, tirolesa e apoio." },
  { n:"Brotas — capital da aventura", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-22.2831, lng:-48.1258, nota:"Cachoeiras, rafting e cascatismo; muitos campings e ranchos." },
  { n:"Camping Clube — Guarujá", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-23.9944, lng:-46.2564, nota:"Litoral da Baixada Santista; unidade do Camping Clube." },
  { n:"Ouro Preto / Lavras Novas", uf:"MG", reg:"Sudeste", tipo:"camping", lat:-20.3856, lng:-43.5035, nota:"Cidades históricas; pousadas-camping em Lavras Novas." },
  { n:"Tiradentes / São João del-Rei", uf:"MG", reg:"Sudeste", tipo:"apoio", lat:-21.1103, lng:-44.1750, nota:"Barroco mineiro e Maria-Fumaça; apoio e gastronomia." },
  { n:"Serra do Cipó — Cardeal Mota", uf:"MG", reg:"Sudeste", tipo:"camping", lat:-19.3270, lng:-43.6160, nota:"Vários campings na MG-010, junto ao PARNA; cachoeiras e cânions." },
  { n:"Camping Véu da Noiva (Serra do Cipó)", uf:"MG", reg:"Sudeste", tipo:"camping", lat:-19.3389, lng:-43.6028, nota:"Tradicional, no circuito do parque; perto da cachoeira." },
  { n:"Lapinha da Serra", uf:"MG", reg:"Sudeste", tipo:"camping", lat:-19.2833, lng:-43.6333, nota:"Vila bucólica com lago e Morro da Carapuça; campings simples." },
  { n:"Milho Verde / Serro", uf:"MG", reg:"Sudeste", tipo:"camping", lat:-18.4560, lng:-43.4350, nota:"Vila serrana do Espinhaço; queijo do Serro e cachoeiras." },
  { n:"São Thomé das Letras", uf:"MG", reg:"Sudeste", tipo:"camping", lat:-21.7239, lng:-44.9869, nota:"Cidade de pedra e mística; campings com vista do vale." },
  { n:"Aiuruoca / Vale do Matutu", uf:"MG", reg:"Sudeste", tipo:"camping", lat:-21.9760, lng:-44.6040, nota:"Pico do Papagaio e cachoeiras; campings à beira de rio (ex.: O Panorâmico, Km 10 da estrada do Matutu)." },
  { n:"Ibitipoca (Conceição do Ibitipoca)", uf:"MG", reg:"Sudeste", tipo:"parque", lat:-21.7086, lng:-43.8917, nota:"Parque Estadual do Ibitipoca; grutas, cachoeiras e a Janela do Céu. Campings na vila do Ibitipoca." },
  { n:"Carrancas — cachoeiras", uf:"MG", reg:"Sudeste", tipo:"camping", lat:-21.4886, lng:-44.6494, nota:"Complexo da Zilda, Fumaça e poços; muitos campings rurais." },
  { n:"Gonçalves (Mantiqueira)", uf:"MG", reg:"Sudeste", tipo:"camping", lat:-22.6567, lng:-45.8556, nota:"Refúgio de montanha na Mantiqueira; campings e trilhas." },
  { n:"Monte Verde (Camanducaia)", uf:"MG", reg:"Sudeste", tipo:"apoio", lat:-22.8636, lng:-46.0364, nota:"Vila alpina de altitude; frio, fondue e trilhas." },
  { n:"Serra da Canastra (São Roque de Minas)", uf:"MG", reg:"Sudeste", tipo:"parque", lat:-20.2467, lng:-46.3667, nota:"Nascente do São Francisco e Casca d'Anta; campings e portaria." },
  { n:"Capitólio / Escarpas de Furnas", uf:"MG", reg:"Sudeste", tipo:"camping", lat:-20.6156, lng:-46.0489, nota:"Cânions do lago de Furnas; campings e passeios de lancha." },
  { n:"PETAR — Núcleo Santana (Iporanga)", uf:"SP", reg:"Sudeste", tipo:"parque", lat:-24.5253, lng:-48.6903, nota:"Parque das cavernas do Alto Ribeira; campings nos núcleos, grutas e rios." },
  { n:"Ilha do Cardoso (Cananéia)", uf:"SP", reg:"Sudeste", tipo:"parque", lat:-25.1281, lng:-47.9297, nota:"Ilha preservada no litoral sul; camping no Marujá, acesso por barco." },
  { n:"São Luiz do Paraitinga", uf:"SP", reg:"Sudeste", tipo:"apoio", lat:-23.2222, lng:-45.3106, nota:"Cidade histórica e cachoeiras; base para o PE da Serra do Mar." },
  { n:"Praia do Sono (Paraty)", uf:"RJ", reg:"Sudeste", tipo:"camping", lat:-23.3050, lng:-44.5433, nota:"Praia isolada com trilha ou barco; campings pé na areia." },
  { n:"Itaúnas (Conceição da Barra)", uf:"ES", reg:"Sudeste", tipo:"camping", lat:-18.4200, lng:-39.6939, nota:"Dunas, Parque Estadual e Festival de Forró (jul); vários campings na vila." },
  { n:"Pedra Azul (Domingos Martins)", uf:"ES", reg:"Sudeste", tipo:"parque", lat:-20.4053, lng:-41.0189, nota:"Monólito de 1.822 m na região serrana capixaba; campings e pousadas." },
  { n:"Guarapari / Setiba (Paulo César Vinha)", uf:"ES", reg:"Sudeste", tipo:"parque", lat:-20.5889, lng:-40.4131, nota:"Praias e restinga preservada; camping e lagoas no litoral capixaba." },
  { n:"PARNA Serra dos Órgãos (Teresópolis)", uf:"RJ", reg:"Sudeste", tipo:"parque", lat:-22.4522, lng:-42.9922, nota:"Dedo de Deus e a travessia Petrópolis–Teresópolis; camping no núcleo do parque." },
  { n:"Lumiar / São Pedro da Serra (Nova Friburgo)", uf:"RJ", reg:"Sudeste", tipo:"camping", lat:-22.3486, lng:-42.3183, nota:"Rios de poços e cachoeiras na serra fluminense; muitos campings à beira d'água." },
  { n:"Arraial do Cabo", uf:"RJ", reg:"Sudeste", tipo:"apoio", lat:-22.9661, lng:-42.0278, nota:"'Caribe brasileiro'; mar turquesa, mergulho e campings na Região dos Lagos." },
  { n:"Saquarema — Itaúna", uf:"RJ", reg:"Sudeste", tipo:"camping", lat:-22.9317, lng:-42.4753, nota:"Meca do surfe e lagoas; campings próximos à praia de Itaúna." },
  { n:"Maresias / Boiçucanga (São Sebastião)", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-23.7889, lng:-45.5636, nota:"Litoral norte de surfe; campings e apoio entre Maresias e Camburi." },
  { n:"Peruíbe / Estação Juréia", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-24.3200, lng:-47.0000, nota:"Praias selvagens e a Juréia-Itatins; campings no litoral sul paulista." },
  { n:"Conceição do Mato Dentro (Tabuleiro)", uf:"MG", reg:"Sudeste", tipo:"camping", lat:-19.0064, lng:-43.4167, nota:"Cachoeira do Tabuleiro, a maior de MG (273 m); camping no Parque Estadual." },
  { n:"Diamantina", uf:"MG", reg:"Sudeste", tipo:"apoio", lat:-18.2417, lng:-43.6006, nota:"Patrimônio da Humanidade no Espinhaço; base para Biribiri e Milho Verde." },
  { n:"Águas de Lindóia / Serra Negra", uf:"SP", reg:"Sudeste", tipo:"apoio", lat:-22.4753, lng:-46.6322, nota:"Circuito das Águas paulista; termas, teleférico e apoio de estância." },
  { n:"Cunha — estrada Paraty", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-23.0742, lng:-44.9597, nota:"Cerâmica de alta temperatura e a estrada da Bocaina até Paraty; campings rurais." },
  { n:"Ilha Comprida", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-24.7308, lng:-47.5375, nota:"Ilha-barreira de ~70 km no litoral sul; campings e travessia por Iguape." },
  { n:"Águas de São Pedro", uf:"SP", reg:"Sudeste", tipo:"apoio", lat:-22.5989, lng:-47.8731, nota:"Menor município de SP, estância hidromineral; apoio e fontes." },
  { n:"Passa Quatro", uf:"MG", reg:"Sudeste", tipo:"apoio", lat:-22.3897, lng:-44.9631, nota:"Mantiqueira sul-mineira; trem da Serra e base para o Pico da Bandeira e Marmelópolis." },
  { n:"Poços de Caldas", uf:"MG", reg:"Sudeste", tipo:"apoio", lat:-21.7878, lng:-46.5619, nota:"Estância hidromineral em caldeira vulcânica; apoio, termas e mirantes." },
  { n:"Brumadinho / Inhotim", uf:"MG", reg:"Sudeste", tipo:"apoio", lat:-20.1436, lng:-44.1958, nota:"Maior museu de arte a céu aberto da América Latina; apoio na região metropolitana de BH." },
  { n:"Cabo Frio / Búzios", uf:"RJ", reg:"Sudeste", tipo:"apoio", lat:-22.8894, lng:-42.0286, nota:"Região dos Lagos; praias de areia branca, dunas e apoio completo." },
  { n:"Petrópolis", uf:"RJ", reg:"Sudeste", tipo:"apoio", lat:-22.5050, lng:-43.1786, nota:"Cidade imperial na serra fluminense; base para a Serra dos Órgãos e o Vale do Caí." },
  { n:"Delfinópolis (Furnas/Canastra)", uf:"MG", reg:"Sudeste", tipo:"camping", lat:-20.3450, lng:-46.8500, nota:"Cânions e grutas no lago de Furnas, borda da Canastra; campings e passeios de barco." },
  { n:"Itamonte / Serra Fina", uf:"MG", reg:"Sudeste", tipo:"camping", lat:-22.2842, lng:-44.8672, nota:"Base da trilha da Serra Fina e do Vale dos Garcias; campings de montanha na Mantiqueira." },
  { n:"Alagoa (queijos)", uf:"MG", reg:"Sudeste", tipo:"camping", lat:-22.1650, lng:-44.6408, nota:"Terra do premiado queijo Alagoa; vilarejo de montanha com campings e cachoeiras." },
  { n:"Alto Caparaó / Pico da Bandeira", uf:"MG", reg:"Sudeste", tipo:"parque", lat:-20.4197, lng:-41.8622, nota:"PARNA do Caparaó; base para o Pico da Bandeira (2.892 m), com camping na Tronqueira." },
  { n:"Serra do Brigadeiro (Fervedouro)", uf:"MG", reg:"Sudeste", tipo:"parque", lat:-20.7167, lng:-42.4833, nota:"Mata atlântica de altitude na Zona da Mata; muriquis, mirantes e campings do parque." },
  { n:"Intervales (Ribeirão Grande)", uf:"SP", reg:"Sudeste", tipo:"parque", lat:-24.2667, lng:-48.4167, nota:"Parque Estadual de mata atlântica contínua; grutas, aves e alojamento/camping." },
  { n:"Belo Horizonte", uf:"MG", reg:"Sudeste", tipo:"apoio", lat:-19.9167, lng:-43.9345, nota:"Capital mineira; apoio urbano e base para a região metropolitana e o Espinhaço." },
  { n:"Uberlândia", uf:"MG", reg:"Sudeste", tipo:"apoio", lat:-18.9186, lng:-48.2772, nota:"Maior cidade do Triângulo Mineiro; apoio logístico entre MG, GO e SP." },
  { n:"Governador Valadares", uf:"MG", reg:"Sudeste", tipo:"apoio", lat:-18.8511, lng:-41.9494, nota:"Vale do Rio Doce; apoio a caminho do Parque do Caparaó e do litoral do ES." },
  { n:"Montes Claros", uf:"MG", reg:"Sudeste", tipo:"apoio", lat:-16.7285, lng:-43.8578, nota:"Portal do norte de Minas; apoio para a Serra do Cipó–Grande Sertão e a Bahia." },
  { n:"Linhares", uf:"ES", reg:"Sudeste", tipo:"camping", lat:-19.3911, lng:-40.0722, nota:"Reserva Natural Vale e o rio Doce; campings próximos a lagoas e mata atlântica preservada." },
  { n:"Vila Velha", uf:"ES", reg:"Sudeste", tipo:"apoio", lat:-20.3297, lng:-40.2925, nota:"Convento da Penha e praias urbanas; apoio na Grande Vitória." },
  { n:"Piúma", uf:"ES", reg:"Sudeste", tipo:"camping", lat:-20.8386, lng:-40.7167, nota:"Avistamento de arraias-manta e praias tranquilas no litoral sul capixaba; campings de temporada." },
  { n:"Rio de Janeiro (Capital)", uf:"RJ", reg:"Sudeste", tipo:"apoio", lat:-22.9068, lng:-43.1729, nota:"Capital fluminense; apoio urbano e base para a Costa Verde, Região dos Lagos e a serra." },
  { n:"Angra dos Reis", uf:"RJ", reg:"Sudeste", tipo:"apoio", lat:-23.0067, lng:-44.3181, nota:"Baía com mais de 300 ilhas; apoio e ponto de partida para passeios náuticos e Ilha Grande." },
  { n:"Rio das Ostras", uf:"RJ", reg:"Sudeste", tipo:"camping", lat:-22.5297, lng:-41.9453, nota:"Praias e lagoas na Região dos Lagos; campings ao longo da orla." },
  { n:"Cachoeiras de Macacu", uf:"RJ", reg:"Sudeste", tipo:"camping", lat:-22.9219, lng:-42.6553, nota:"Portal da Serra dos Órgãos pelo lado leste; cachoeiras e campings rurais." },
  { n:"Maricá", uf:"RJ", reg:"Sudeste", tipo:"camping", lat:-22.9194, lng:-42.8186, nota:"Lagoas e praias extensas entre Niterói e Saquarema; campings próximos à restinga." },

  /* ===================== CENTRO-OESTE ===================== */
  { n:"Chapada dos Veadeiros — Alto Paraíso", uf:"GO", reg:"Centro-Oeste", tipo:"apoio", lat:-14.1330, lng:-47.5100, nota:"Base do cerrado de altitude; cachoeiras e cristais." },
  { n:"São Jorge (Chapada dos Veadeiros)", uf:"GO", reg:"Centro-Oeste", tipo:"camping", lat:-14.1719, lng:-47.8064, nota:"Vila na porta do PARNA; muitos campings e trilhas." },
  { n:"Cavalcante (cachoeiras kalungas)", uf:"GO", reg:"Centro-Oeste", tipo:"camping", lat:-13.7972, lng:-47.4569, nota:"Portal do território kalunga (Santa Bárbara); campings e pousadas." },
  { n:"Pirenópolis", uf:"GO", reg:"Centro-Oeste", tipo:"camping", lat:-15.8514, lng:-48.9581, nota:"Cidade histórica e cachoeiras; campings no entorno." },
  { n:"Chapada dos Guimarães", uf:"MT", reg:"Centro-Oeste", tipo:"parque", lat:-15.4114, lng:-55.7500, nota:"Véu de Noiva e mirantes; camping e apoio na cidade." },
  { n:"Nobres / Bom Jardim", uf:"MT", reg:"Centro-Oeste", tipo:"camping", lat:-14.7183, lng:-56.3275, nota:"Flutuação em rios cristalinos; campings e balneários." },
  { n:"Poconé — início da Transpantaneira", uf:"MT", reg:"Centro-Oeste", tipo:"apoio", lat:-16.2567, lng:-56.6228, nota:"Último apoio completo antes da Transpantaneira (abasteça)." },
  { n:"Porto Jofre (Transpantaneira, fim)", uf:"MT", reg:"Centro-Oeste", tipo:"pernoite", lat:-17.3583, lng:-56.7739, nota:"Fim da estrada, capital da onça-pintada; pousadas e camping." },
  { n:"Bonito", uf:"MS", reg:"Centro-Oeste", tipo:"apoio", lat:-21.1261, lng:-56.4836, nota:"Capital das águas; grutas, flutuação e apoio completo." },
  { n:"Estrada Parque do Pantanal (Passo do Lontra)", uf:"MS", reg:"Centro-Oeste", tipo:"pernoite", lat:-19.5747, lng:-57.0233, nota:"Pousadas de pantanal com camping; fauna abundante." },
  { n:"Camping Clube — Corumbá", uf:"MS", reg:"Centro-Oeste", tipo:"apoio", lat:-19.0092, lng:-57.6531, nota:"Capital do Pantanal, à beira do rio Paraguai; apoio e passeios." },
  { n:"Alto Paraíso — Vale da Lua", uf:"GO", reg:"Centro-Oeste", tipo:"camping", lat:-14.0997, lng:-47.6892, nota:"Rochas do rio São Miguel; campings próximos (não visitar sob chuva)." },
  { n:"Brasília — Chapada Imperial", uf:"DF", reg:"Centro-Oeste", tipo:"camping", lat:-15.5333, lng:-48.1500, nota:"Maior reserva particular do DF; cachoeiras e camping a ~50 km do Plano Piloto." },
  { n:"Camping Clube — Brasília (Lago Paranoá)", uf:"DF", reg:"Centro-Oeste", tipo:"apoio", lat:-15.8000, lng:-47.8256, nota:"Apoio na capital; base para a Chapada dos Veadeiros e Pirenópolis." },
  { n:"Caldas Novas / Rio Quente", uf:"GO", reg:"Centro-Oeste", tipo:"apoio", lat:-17.7442, lng:-48.6250, nota:"Maior estância hidrotermal do mundo; campings e parques de águas quentes." },
  { n:"Aruanã — Rio Araguaia", uf:"GO", reg:"Centro-Oeste", tipo:"camping", lat:-14.9200, lng:-51.0800, nota:"Praias de rio na temporada seca (jul); acampamentos à beira do Araguaia." },
  { n:"Barra do Garças — Rio Araguaia", uf:"MT", reg:"Centro-Oeste", tipo:"camping", lat:-15.8900, lng:-52.2569, nota:"Praias fluviais, águas quentes e a Serra do Roncador; campings na temporada." },
  { n:"Miranda — Estrada Parque / Aquidauana", uf:"MS", reg:"Centro-Oeste", tipo:"pernoite", lat:-20.2419, lng:-56.3778, nota:"Portal sul do Pantanal; fazendas com camping e focagem de fauna." },
  { n:"Jardim — Rio da Prata / Sucuri", uf:"MS", reg:"Centro-Oeste", tipo:"camping", lat:-21.4797, lng:-56.1381, nota:"Flutuação em rios cristalinos e o Buraco das Araras; apoio e campings." },
  { n:"Formosa — Salto do Itiquira", uf:"GO", reg:"Centro-Oeste", tipo:"camping", lat:-15.5386, lng:-47.3339, nota:"Queda de 168 m em parque com estrutura; camping e balneário a ~2 h de Brasília." },
  { n:"Cáceres — Pantanal noroeste", uf:"MT", reg:"Centro-Oeste", tipo:"apoio", lat:-16.0764, lng:-57.6817, nota:"às margens do rio Paraguai; festival de pesca e porta do Pantanal norte." },
  { n:"Coxim — Rio Taquari", uf:"MS", reg:"Centro-Oeste", tipo:"camping", lat:-18.5067, lng:-54.7600, nota:"Capital da piracema; praias de rio, pesca e campings na temporada seca." },
  { n:"Serra da Bodoquena (Bodoquena)", uf:"MS", reg:"Centro-Oeste", tipo:"parque", lat:-20.5378, lng:-56.7128, nota:"Parque Nacional de cachoeiras e grutas entre Bonito e Miranda; apoio na cidade." },
  { n:"Costa Rica — Rio Sucuriú", uf:"MS", reg:"Centro-Oeste", tipo:"camping", lat:-18.5433, lng:-53.1294, nota:"Cachoeiras e sítios arqueológicos no nordeste de MS; campings à beira do Sucuriú." },
  { n:"Goiânia", uf:"GO", reg:"Centro-Oeste", tipo:"apoio", lat:-16.6799, lng:-49.2550, nota:"Capital goiana; apoio urbano e base para a Chapada dos Veadeiros e Pirenópolis." },
  { n:"Terra Ronca (São Domingos)", uf:"GO", reg:"Centro-Oeste", tipo:"parque", lat:-13.6667, lng:-46.3667, nota:"Parque Estadual com um dos maiores complexos de cavernas da América Latina; camping na sede." },

  /* ===================== NORDESTE ===================== */
  { n:"Camping Clube — Guarajuba (Camaçari)", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-12.6539, lng:-38.0117, nota:"Litoral norte baiano; unidade do Camping Clube." },
  { n:"Chapada Diamantina — Lençóis", uf:"BA", reg:"Nordeste", tipo:"apoio", lat:-12.5619, lng:-41.3900, nota:"Base do trekking; Vale do Pati, Fumaça e cachoeiras." },
  { n:"Vale do Capão (Chapada Diamantina)", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-12.6000, lng:-41.5000, nota:"Vila de trilheiros; muitos campings e a Cachoeira da Fumaça." },
  { n:"Mucugê / Igatu (Chapada)", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-13.0053, lng:-41.3711, nota:"Sul da Chapada; Poço Encantado e a 'Machu Picchu baiana'." },
  { n:"Trancoso / Caraíva (Porto Seguro)", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-16.5900, lng:-39.0950, nota:"Costa do Descobrimento; vilas de praia e campings rústicos." },
  { n:"Itacaré", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-14.2769, lng:-38.9967, nota:"Praias de surfe e mata atlântica; campings e pousadas." },
  { n:"Praia do Forte (Mata de São João)", uf:"BA", reg:"Nordeste", tipo:"apoio", lat:-12.5786, lng:-38.0000, nota:"Projeto Tamar e piscinas naturais; apoio na vila." },
  { n:"Jericoacoara", uf:"CE", reg:"Nordeste", tipo:"camping", lat:-2.7936, lng:-40.5136, nota:"Vila de dunas (acesso 4x4); campings e a Duna do Pôr do Sol." },
  { n:"Canoa Quebrada (Aracati)", uf:"CE", reg:"Nordeste", tipo:"camping", lat:-4.5247, lng:-37.7019, nota:"Falésias, buggy e Broadway; campings e pousadas." },
  { n:"Icaraí de Amontada", uf:"CE", reg:"Nordeste", tipo:"camping", lat:-3.0469, lng:-39.6453, nota:"Vila de kitesurf entre dunas (acesso de terra)." },
  { n:"Barreirinhas (Lençóis Maranhenses)", uf:"MA", reg:"Nordeste", tipo:"apoio", lat:-2.7550, lng:-42.8261, nota:"Base do parque; circuito Lagoa Azul e rio Preguiças." },
  { n:"Atins (Lençóis Maranhenses)", uf:"MA", reg:"Nordeste", tipo:"camping", lat:-2.5772, lng:-42.7339, nota:"Vila rústica na foz; kite e entrada selvagem dos Lençóis." },
  { n:"Delta do Parnaíba (Tutóia)", uf:"MA", reg:"Nordeste", tipo:"pernoite", lat:-2.7614, lng:-42.2739, nota:"Portal do delta e dos Pequenos Lençóis; passeios de barco." },
  { n:"Pipa / Tibau do Sul", uf:"RN", reg:"Nordeste", tipo:"camping", lat:-6.2281, lng:-35.0450, nota:"Falésias, golfinhos e Lagoa de Guaraíras; campings e pousadas." },
  { n:"São Miguel do Gostoso", uf:"RN", reg:"Nordeste", tipo:"camping", lat:-5.1214, lng:-35.6367, nota:"Vento constante para kite; vila tranquila com campings." },
  { n:"Maragogi (Costa dos Corais)", uf:"AL", reg:"Nordeste", tipo:"apoio", lat:-9.0122, lng:-35.2225, nota:"Galés e piscinas naturais de recife; apoio na orla." },
  { n:"São Miguel dos Milagres", uf:"AL", reg:"Nordeste", tipo:"camping", lat:-9.2650, lng:-35.3650, nota:"Rota Ecológica de recifes; vilas calmas e campings." },
  { n:"Porto de Galinhas (Ipojuca)", uf:"PE", reg:"Nordeste", tipo:"apoio", lat:-8.5089, lng:-35.0072, nota:"Piscinas naturais e jangadas; grande apoio turístico." },
  { n:"Praia da Pipa — Chapadão", uf:"RN", reg:"Nordeste", tipo:"pernoite", lat:-6.2333, lng:-35.0389, nota:"Mirante das falésias; áreas de pernoite com vista." },
  { n:"João Pessoa — Praia do Jacaré", uf:"PB", reg:"Nordeste", tipo:"apoio", lat:-7.0472, lng:-34.8503, nota:"Pôr do sol com Bolero de Ravel no rio Paraíba; apoio na capital." },
  { n:"Serra da Capivara (São Raimundo Nonato)", uf:"PI", reg:"Nordeste", tipo:"parque", lat:-8.8367, lng:-42.5583, nota:"Patrimônio da Humanidade; pinturas rupestres e cânions. Apoio em Coronel José Dias." },
  { n:"Sete Cidades (Piripiri)", uf:"PI", reg:"Nordeste", tipo:"parque", lat:-4.0961, lng:-41.7089, nota:"Formações rochosas e inscrições; camping do parque nacional." },
  { n:"Cânion do Xingó (Canindé de São Francisco)", uf:"SE", reg:"Nordeste", tipo:"camping", lat:-9.6217, lng:-37.7897, nota:"Passeios de catamarã pelos paredões do São Francisco; apoio e campings." },
  { n:"Praia do Saco (Estância)", uf:"SE", reg:"Nordeste", tipo:"camping", lat:-11.3672, lng:-37.4033, nota:"Litoral sul sergipano; dunas, coqueirais e campings." },
  { n:"Fernando de Noronha", uf:"PE", reg:"Nordeste", tipo:"camping", lat:-3.8547, lng:-32.4247, nota:"Arquipélago-santuário; campings credenciados na Vila do Trinta (taxa ambiental à parte)." },
  { n:"Cumbuco (Caucaia)", uf:"CE", reg:"Nordeste", tipo:"camping", lat:-3.6300, lng:-38.7300, nota:"Dunas, lagoas e kitesurf perto de Fortaleza; campings e buggy." },
  { n:"Morro Branco / Praia das Fontes (Beberibe)", uf:"CE", reg:"Nordeste", tipo:"camping", lat:-4.1489, lng:-38.1400, nota:"Falésias coloridas e labirintos; campings no litoral leste cearense." },
  { n:"Genipabu (Extremoz)", uf:"RN", reg:"Nordeste", tipo:"camping", lat:-5.6706, lng:-35.2464, nota:"Dunas móveis e passeio de dromedário; campings e buggy perto de Natal." },
  { n:"Galinhos", uf:"RN", reg:"Nordeste", tipo:"camping", lat:-5.0917, lng:-36.2733, nota:"Península de salinas e dunas (acesso por barco/4x4); vila tranquila com campings." },
  { n:"Morro de São Paulo / Boipeba (Cairu)", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-13.3833, lng:-38.9167, nota:"Ilha de Tinharé sem carros; campings nas praias e travessia de barco." },
  { n:"Mangue Seco (Jandaíra)", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-11.4239, lng:-37.1039, nota:"Dunas na divisa BA/SE, cenário de 'Tieta'; campings rústicos e travessia de barco." },
  { n:"Japaratinga / Barra de São Miguel", uf:"AL", reg:"Nordeste", tipo:"camping", lat:-9.0894, lng:-35.2558, nota:"Piscinas naturais e coqueirais da costa alagoana; campings à beira-mar." },
  { n:"Tambaba / Praia de Tabatinga (Conde)", uf:"PB", reg:"Nordeste", tipo:"camping", lat:-7.3283, lng:-34.8047, nota:"Falésias e a primeira praia de naturismo oficial do Nordeste; campings no litoral sul da PB." },
  { n:"Cabo de Santo Agostinho", uf:"PE", reg:"Nordeste", tipo:"camping", lat:-8.2897, lng:-35.0353, nota:"Praias de Calhetas e Gaibu, fortes históricos e o marco de Tordesilhas; campings próximos." },
  { n:"Tamandaré / Praia dos Carneiros", uf:"PE", reg:"Nordeste", tipo:"camping", lat:-8.7597, lng:-35.1044, nota:"Piscinas de recife e a capelinha na praia; campings e apoio no litoral sul pernambucano." },
  { n:"Barra Grande (Maraú)", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-14.1656, lng:-38.9800, nota:"Península de Maraú com praias desertas e a piscina do Taiípe; campings e pousadas rústicas." },
  { n:"Aracaju — Praia do Atalaia", uf:"SE", reg:"Nordeste", tipo:"apoio", lat:-10.9853, lng:-37.0500, nota:"Capital sergipana; orla, Oceanário e base para a Croa do Goé e o litoral sul." },
  { n:"Baía Formosa", uf:"RN", reg:"Nordeste", tipo:"camping", lat:-6.3719, lng:-35.0072, nota:"Vila de pesca e surfe com Mata Estrela e lagoa de água doce; campings tranquilos." },
  { n:"Icapuí / Ponta Grossa", uf:"CE", reg:"Nordeste", tipo:"camping", lat:-4.7139, lng:-37.3556, nota:"Falésias, recifes e vila de pescadores no extremo leste cearense; campings tranquilos." },
  { n:"Paracuru / Lagoinha", uf:"CE", reg:"Nordeste", tipo:"camping", lat:-3.4100, lng:-39.0300, nota:"Surfe, kite e coqueirais perto de Fortaleza; campings e a badalada Lagoinha." },
  { n:"Ilha de Itamaracá", uf:"PE", reg:"Nordeste", tipo:"camping", lat:-7.7478, lng:-34.8261, nota:"Forte Orange, peçois-boi e praias calmas; campings na ilha ao norte de Recife." },
  { n:"Piranhas / Cânion do Xingó (AL)", uf:"AL", reg:"Nordeste", tipo:"camping", lat:-9.6244, lng:-37.7561, nota:"Cidade histórica às margens do São Francisco; catamarã pelo cânion e rota do cangao." },
  { n:"RV Park Gameleira (Coruripe)", uf:"AL", reg:"Nordeste", tipo:"pernoite", lat:-10.1330, lng:-36.1497, nota:"Estrutura para motorhome/RV na praia da Gameleira, litoral sul de Alagoas (Pontal do Coruripe): pernoite, apoio e coqueirais à beira-mar." },
  { n:"Ilhéus", uf:"BA", reg:"Nordeste", tipo:"apoio", lat:-14.7889, lng:-39.0494, nota:"Terra de Jorge Amado e do cacau; apoio na Costa do Cacau, entre Itacaré e Olivença." },
  { n:"Salvador", uf:"BA", reg:"Nordeste", tipo:"apoio", lat:-12.9714, lng:-38.5014, nota:"Capital baiana; Pelourinho e apoio urbano, base para a Costa dos Coqueiros e Chapada." },
  { n:"Arraial d'Ajuda", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-16.4772, lng:-39.0806, nota:"Vila de charme na Costa do Descobrimento, ao lado de Porto Seguro; campings e travessia de balsa." },
  { n:"Prado", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-17.3400, lng:-39.2211, nota:"Praias desertas e recifes de coral no extremo sul baiano; campings tranquilos." },
  { n:"Cumuruxatiba", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-17.0961, lng:-39.1922, nota:"Vila de pescadores com falésias e observação de baleias jubarte (jul–nov); campings na praia." },
  { n:"Tianguá (Ubajara)", uf:"CE", reg:"Nordeste", tipo:"apoio", lat:-3.6314, lng:-40.9931, nota:"Porta de entrada do Parque Nacional de Ubajara, com teleférico e grutas; apoio na serra." },
  { n:"Caruaru", uf:"PE", reg:"Nordeste", tipo:"apoio", lat:-8.2828, lng:-35.9761, nota:"Capital do São João e do forró; apoio no Agreste pernambucano." },
  { n:"Olinda", uf:"PE", reg:"Nordeste", tipo:"apoio", lat:-8.0089, lng:-34.8553, nota:"Patrimônio da Humanidade, ladeiras coloniais e Carnaval; apoio ao lado de Recife." },

  /* ===================== NORTE ===================== */
  { n:"Presidente Figueiredo", uf:"AM", reg:"Norte", tipo:"camping", lat:-2.0300, lng:-60.0250, nota:"Terra das cachoeiras, ao norte de Manaus; campings e grutas." },
  { n:"Alter do Chão (Santarém)", uf:"PA", reg:"Norte", tipo:"camping", lat:-2.5072, lng:-54.9469, nota:"'Caribe amazônico'; praias de rio e Ilha do Amor." },
  { n:"Jalapão (Ponte Alta do Tocantins)", uf:"TO", reg:"Norte", tipo:"camping", lat:-10.7561, lng:-47.5361, nota:"Dunas, fervedouros e cachoeiras (acesso 4x4); campings rústicos." },
  { n:"Chapada das Mesas (Carolina)", uf:"MA", reg:"Norte", tipo:"camping", lat:-7.3350, lng:-47.4650, nota:"Cachoeiras e cânions do cerrado maranhense; campings na região." },
  { n:"Serra do Tepequém (Amajari)", uf:"RR", reg:"Norte", tipo:"camping", lat:3.7614, lng:-61.7189, nota:"Serra de garimpo com cachoeiras e mirantes; campings rústicos em Roraima." },
  { n:"Boa Vista — base do Tepequém/fronteira", uf:"RR", reg:"Norte", tipo:"apoio", lat:2.8235, lng:-60.6758, nota:"Capital planejada; apoio e ponto de partida para o Tepequém e a fronteira." },
  { n:"Porto Velho / Flona do Jamari", uf:"RO", reg:"Norte", tipo:"apoio", lat:-8.7619, lng:-63.9039, nota:"Base no rio Madeira; apoio urbano e a Floresta Nacional do Jamari a ~90 km." },
  { n:"Rio Branco — Parque Chico Mendes", uf:"AC", reg:"Norte", tipo:"apoio", lat:-9.9750, lng:-67.8100, nota:"Capital acreana; apoio e base para a Amazônia ocidental e o Peru." },
  { n:"Macapá — Marco Zero do Equador", uf:"AP", reg:"Norte", tipo:"apoio", lat:0.0389, lng:-51.0664, nota:"Cidade sobre a linha do Equador; Fortaleza de São José e foz do Amazonas." },
  { n:"Novo Airão — Anavilhanas", uf:"AM", reg:"Norte", tipo:"apoio", lat:-2.6289, lng:-60.9436, nota:"Portal do arquipélago de Anavilhanas no rio Negro; apoio e passeios de barco." },
  { n:"Salinópolis — Praia do Atalaia", uf:"PA", reg:"Norte", tipo:"camping", lat:-0.6136, lng:-47.3561, nota:"Praias de mar aberto na Amazônia atlântica; campings e barracas na temporada." },
  { n:"Ilha de Marajó (Soure)", uf:"PA", reg:"Norte", tipo:"camping", lat:-0.7167, lng:-48.5233, nota:"Maior ilha fluviomarinha do mundo; búfalos, praias de rio e campings rústicos." },
  { n:"Taquaruçu (Palmas)", uf:"TO", reg:"Norte", tipo:"camping", lat:-10.3167, lng:-48.1500, nota:"Serra do Lajeado com dezenas de cachoeiras; campings perto da capital." },
  { n:"Manaus — apoio Amazônia", uf:"AM", reg:"Norte", tipo:"apoio", lat:-3.1019, lng:-60.0250, nota:"Encontro das Águas e Teatro Amazonas; base logística para o rio Negro e Anavilhanas." },
  { n:"Belém — apoio", uf:"PA", reg:"Norte", tipo:"apoio", lat:-1.4558, lng:-48.5000, nota:"Ver-o-Peso, Mangal das Garças e Estação das Docas; porta da Amazônia oriental e do Marajó." },
  { n:"Palmas — Praia da Graciosa", uf:"TO", reg:"Norte", tipo:"apoio", lat:-10.1689, lng:-48.3317, nota:"Capital às margens do lago do Lajeado; praia urbana e apoio para o Jalapão." },
  { n:"Mateiros (núcleo do Jalapão)", uf:"TO", reg:"Norte", tipo:"camping", lat:-10.5533, lng:-46.4167, nota:"Coração do Jalapão: Dunas, Fervedouro e cachoeiras; campings rústicos (acesso 4x4)." },
  { n:"Oiapoque — extremo norte", uf:"AP", reg:"Norte", tipo:"apoio", lat:3.8408, lng:-51.8353, nota:"Fronteira com a Guiana Francesa, na foz do rio Oiapoque; ponto extremo norte do Brasil." },
  { n:"Cruzeiro do Sul", uf:"AC", reg:"Norte", tipo:"apoio", lat:-7.6306, lng:-72.6710, nota:"Vale do Juruá, no extremo oeste acreano; farinha, floresta e o Parque da Serra do Divisor." },


  /* ===================== COMUNIDADE PROMOVIDA (OSM, tags ricas) ===================== */
  { n:"Camping Mucugê", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-13.0257, lng:-41.43895, nota:"Aceita motorhome, barraca, chuveiro/banheiro/água potável/energia/wi-fi. tel. +55 75 98158 5453 · campingmucuge.com.br/chapada-diamantina (OSM)" , ig:"campingmucuge"},
  { n:"Camping e hostel Xique Xique", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-12.8959, lng:-41.31936, nota:"Barraca, chuveiro/banheiro/água potável/energia/wi-fi. tel. +55 71 98838 4233 · abrigoxiquexique.com (OSM)" },
  { n:"República Lago (Leme)", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-22.22618, lng:-47.29866, nota:"Chuveiro/banheiro/água potável/energia. tel. +55 11 3818 6600 · replago.com.br (OSM)" },
  { n:"Marina Porto Abrolhos", uf:"ES", reg:"Sudeste", tipo:"camping", lat:-17.7266, lng:-39.17795, nota:"Aceita motorhome, barraca, piscina. tel. +55 73 3674 1060 · www.marinaportoabrolhos.com.br (OSM)" , ig:"hotelmarinaportoabrolhos"},
  { n:"Pantanal Ranch Mandovi", uf:"MS", reg:"Centro-Oeste", tipo:"pernoite", lat:-20.25313, lng:-56.35018, nota:"Energia/wi-fi. tel. +55 67 99292 3342 · www.pantanalranchmandovi.com (OSM)" },
  { n:"Lakshimi", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-12.61121, lng:-41.4987, nota:"Aceita motorhome, barraca, chuveiro/banheiro/água potável/energia/wi-fi. (OSM)" },
  { n:"Camping do Rancho", uf:"RJ", reg:"Sudeste", tipo:"camping", lat:-23.21029, lng:-44.71811, nota:"Wi-fi. tel. +55 24 99885 2054 · ranchodomineiro.com (OSM)" },
  { n:"Costa do Sol", uf:"SC", reg:"Sul", tipo:"camping", lat:-27.42785, lng:-48.4484, nota:"Banheiro/wi-fi. tel. +55 48 3266-1799 · www.campingcostadosol.com.br (OSM)" },
  { n:"Eco Camping e Alojamento Casa da Grota", uf:"SC", reg:"Sul", tipo:"camping", lat:-29.169, lng:-49.98277, nota:"Wi-fi. tel. +5548998677992 · www.instagram.com/sitiocasadagrota (OSM)" , ig:"sitiocasadagrota"},
  { n:"Reserva Angelina", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-12.8071, lng:-41.32337, nota:"Aceita motorhome, barraca, chuveiro/banheiro/água potável/energia/wi-fi. (OSM)" },
  { n:"Camping da família", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-24.7488, lng:-47.55391, nota:"Chuveiro/banheiro/energia/wi-fi. www.facebook.com/pages/Camping-Da-Familiailha-Comprida/708283539247732 (OSM)" },
  { n:"Pousada e Camping Lumiar", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-12.56422, lng:-41.38931, nota:"Aceita motorhome, barraca, chuveiro/banheiro/água potável/energia. (OSM)" , ig:"lumiarpousadaecamping"},
  { n:"Rincão Clube Naturista", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-22.94703, lng:-45.10222, nota:"Chuveiro/banheiro. www.rincaonaturista.com (OSM)" , ig:"naturismorincao"},
  { n:"Camping do senandes", uf:"RS", reg:"Sul", tipo:"camping", lat:-32.14538, lng:-52.19779, nota:"Wi-fi. tel. +55 53 3236-9120 · campingdosenandes.com.br (OSM)" },
  { n:"Camping da Dona Zilá", uf:"RJ", reg:"Sudeste", tipo:"camping", lat:-23.18129, lng:-44.34145, nota:"Barraca, chuveiro/banheiro/água potável/energia. tel. +55 24 99880-9550 (OSM)" },
  { n:"Camping Sítio Pousada", uf:"RS", reg:"Sul", tipo:"camping", lat:-27.05634, lng:-52.70591, nota:"Wi-fi. tel. +55 49 3330 0072 · sitiopousada.blogspot.com.br (OSM)" },
  { n:"Camping Ô Xatiba", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-17.11066, lng:-39.18283, nota:"Wi-fi. tel. +55 73 9 8844-3090 · www.facebook.com/Camping-Ô-Xatiba-149193278772122/?ref=ts&fref=ts (OSM)" , ig:"oxatiba"},
  { n:"Capuba Camping", uf:"ES", reg:"Sudeste", tipo:"camping", lat:-20.10772, lng:-40.17318, nota:"Wi-fi. tel. +55 27 99958-1639 · www.facebook.com/Campingcapuba (OSM)" , ig:"capuba.camping"},
  { n:"Camping e Pousada Serra e Mar", uf:"RS", reg:"Sul", tipo:"camping", lat:-28.98667, lng:-49.43695, nota:"Wi-fi. tel. +5548984901594 · m.facebook.com/pousadacampingserraemar (OSM)" },
  { n:"Morada da Lua Hospedaria Ecológica", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-12.75764, lng:-38.1652, nota:"Estrutura de camping. tel. +55 71 99412 3015 · instagram.com/moradadaluahospedariaecologica (OSM)" , ig:"moradadaluahospedariaecologica"},
  { n:"Camping Beira Mar", uf:"PR", reg:"Sul", tipo:"pernoite", lat:-25.63638, lng:-48.42847, nota:"Wi-fi. tel. +55 41 9 9974 7703 · www.campingbeiramar.com.br (OSM)" , ig:"campingbeiramar"},
  { n:"Camping Seguro Pico do Olho D'Água", uf:"MG", reg:"Sudeste", tipo:"camping", lat:-23.29671, lng:-46.58321, nota:"Barraca. tel. +55 11 95088-8893 · campingmairipora.com.br (OSM)" },
  { n:"Camping d'Itapoá", uf:"PR", reg:"Sul", tipo:"camping", lat:-26.09397, lng:-48.60434, nota:"Wi-fi. tel. +55 47 3443-0814 · www.itapoa.sc.gov.br/turismo/item/detalhe/11161 (OSM)" , ig:"campingpraiaditapoa"},
  { n:"Hotel Parque de Lagoa", uf:"RS", reg:"Sul", tipo:"camping", lat:-31.2888, lng:-51.09036, nota:"Wi-fi. tel. +55 51 3674-1333 · hotelparquedalagoa.com.br (OSM)" },
  { n:"Balneário Poço do Caixão", uf:"RS", reg:"Sul", tipo:"camping", lat:-28.81461, lng:-49.88143, nota:"Aceita motorhome, barraca, banheiro. tel. +554835361099 (OSM)" , ig:"campingpocodocaixao"},
  { n:"Camping Verde Mar", uf:"RJ", reg:"Sudeste", tipo:"camping", lat:-23.01226, lng:-43.51581, nota:"Estrutura de camping. tel. +55 21 2428 3417 · www.campingverdemar.com.br (OSM)" },
  { n:"Recanto do Dário", uf:"RS", reg:"Sul", tipo:"camping", lat:-26.09113, lng:-53.11787, nota:"Estrutura de camping. tel. +55 46 99974 1465 · www.recantododario.com.br/site (OSM)" },
  { n:"Mirante das Águas - Cachoeira Saltão", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-22.3911, lng:-47.8857, nota:"Estrutura de camping. tel. +55 19 99815-0123;+55 19 97164-3123;+55 19 3294-4774 · www.saltao.com.br (OSM)" },
  { n:"Camping Sununga", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-23.50863, lng:-45.13262, nota:"Barraca, wi-fi. sunungakamp.wordpress.com (OSM)" , ig:"sunungacampingbrasil"},
  { n:"Camping Cantão", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-23.86252, lng:-46.13149, nota:"Estrutura de camping. tel. +55 13 99612 2575 · www.campingcantao.com.br (OSM)" , ig:"campingcantaoprainha"},
  { n:"Camping Tabajara", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-23.86333, lng:-46.13258, nota:"Estrutura de camping. tel. +55 13 99734 2798 · www.campingtabajara.com (OSM)" , ig:"campingtabajara"},
  { n:"Camping João Míneíro", uf:"MG", reg:"Sudeste", tipo:"camping", lat:-21.12205, lng:-44.15816, nota:"Aceita motorhome, barraca, chuveiro/energia, piscina. (OSM)" },
  { n:"Camping Padang Surf", uf:"SP", reg:"Sudeste", tipo:"camping", lat:-23.39474, lng:-45.00983, nota:"Aceita motorhome, barraca, chuveiro/banheiro/energia. (OSM)" , ig:"padangsurfcamping"},
  { n:"Camping Família X", uf:"SC", reg:"Sul", tipo:"camping", lat:-27.75124, lng:-49.46564, nota:"Estrutura de camping. tel. +55 48 99819-4418 · www.facebook.com/campingfamiliax (OSM)" },
  { n:"Pousada e Camping Encantos do Sul", uf:"RS", reg:"Sul", tipo:"pernoite", lat:-29.77132, lng:-50.21696, nota:"Estrutura de camping. tel. +55 51 99599-7779 · www.encantosdosul.com.br (OSM)" },
  { n:"Aldeia Maracajaú", uf:"RN", reg:"Nordeste", tipo:"camping", lat:-5.41576, lng:-35.3098, nota:"Chuveiro/banheiro/wi-fi. tel. +55 84 999172874 (OSM)" , ig:"aldeiamaracajau"},
  { n:"Camping Gamboa", uf:"BA", reg:"Nordeste", tipo:"camping", lat:-13.39461, lng:-38.93754, nota:"Wi-fi. tel. +55 75 98312 2810; +55 75 98176 8572; +55 75 3653 7074 · camping.gamboa.com.br (OSM)" },
  { n:"Camping do PikoSam", uf:"RJ", reg:"Sudeste", tipo:"camping", lat:-22.25217, lng:-44.48233, nota:"Chuveiro/energia. www.campingdopikosam.com.br/o-camping (OSM)" , ig:"campingdopikosam"},
  { n:"Recanto das Acácias", uf:"GO", reg:"Centro-Oeste", tipo:"camping", lat:-15.7996, lng:-48.80559, nota:"Aceita motorhome, barraca, banheiro/wi-fi. (OSM)" },
  { n:"Glamping Meraki Brasil", uf:"PR", reg:"Sul", tipo:"camping", lat:-25.40348, lng:-48.76642, nota:"Wi-fi. tel. +55 41 99201 5410 · www.instagram.com/glamping_merakibrasil (OSM)" , ig:"glamping_merakibrasil"},

];
